const {createClient}=window.supabase;
const configured=SUPABASE_URL.startsWith("http") && !SUPABASE_ANON_KEY.includes("PEGA_AQUI");
const db=configured?createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
const MEN_A=["Fortnite","Papitos","Trocos","Chifladitos","Finqueros"];
const MEN_B=["Sin Esquinas","Osos","Motoneta","La Banca","Razitos"];
const WOMEN=["Tan G Neras FC","Osas Mañosas","Las Cabritas","Trocas","Chapiadoras.com","Jags"];

let session=null;
document.addEventListener("DOMContentLoaded",async()=>{document.getElementById("loginBtn").onclick=openModal;document.getElementById("authAction").onclick=auth;document.getElementById("addSanctionBtn").onclick=()=>openSanctionForm();await refresh()});
function openModal(){document.getElementById("authModal").classList.remove("hidden")}
function closeModal(){document.getElementById("authModal").classList.add("hidden")}
function closeEdit(){document.getElementById("editModal").classList.add("hidden")}
async function refresh(){if(!db){renderDemo();return} const {data}=await db.auth.getSession();session=data.session;setEditorUI(); await Promise.all([renderTables(),renderMatches(),renderSanctions(),renderNext()])}
function setEditorUI(){let b=document.getElementById("loginBtn");b.textContent=session?"Cerrar sesión":"Iniciar sesión";b.onclick=session?logout:openModal;document.getElementById("addSanctionBtn").classList.toggle("hidden",!session)}
async function auth(){let email=document.getElementById("email").value,password=document.getElementById("password").value;let r=await db.auth.signInWithPassword({email,password});document.getElementById("authMsg").textContent=r.error?r.error.message:"Acceso correcto";if(!r.error){session=r.data.session;closeModal();setEditorUI();refresh()}}
async function logout(){await db.auth.signOut();session=null;setEditorUI();refresh()}
function stats(teams,matches){return teams.map(t=>{let x={team:t,pj:0,pg:0,pe:0,pp:0,gf:0,gc:0,pts:0};matches.filter(m=>m.home_team===t||m.away_team===t).forEach(m=>{if(m.home_score==null||m.away_score==null)return;let h=m.home_team===t,a=h?m.home_score:m.away_score,b=h?m.away_score:m.home_score;x.pj++;x.gf+=a;x.gc+=b;if(a>b){x.pg++;x.pts+=3}else if(a===b){x.pe++;x.pts++}else x.pp++});x.dg=x.gf-x.gc;return x}).sort((a,b)=>b.pts-a.pts||b.dg-a.dg||b.gf-a.gf)}
function tableHTML(title,data){return `<div class="card"><h3>${title}</h3><div class="table-wrap"><table><thead><tr><th>#</th><th>Equipo</th><th>PJ</th><th>PG</th><th>PE</th><th>PP</th><th>GF</th><th>GC</th><th>DG</th><th>PTS</th></tr></thead><tbody>${data.map((x,i)=>`<tr><td class="rank">${i+1}</td><td><strong>${x.team}</strong></td><td>${x.pj}</td><td>${x.pg}</td><td>${x.pe}</td><td>${x.pp}</td><td>${x.gf}</td><td>${x.gc}</td><td>${x.dg>0?"+":""}${x.dg}</td><td class="pts">${x.pts}</td></tr>`).join("")}</tbody></table></div></div>`}
async function getMatches(){let {data,error}=await db.from("matches").select("*").order("day");if(error)throw error;return data||[]}
async function renderTables(){let ms=await getMatches();document.getElementById("menTables").innerHTML=tableHTML("Grupo A",stats(MEN_A,ms.filter(m=>m.gender==="M"&&m.group_name==="A")))+tableHTML("Grupo B",stats(MEN_B,ms.filter(m=>m.gender==="M"&&m.group_name==="B")));document.getElementById("womenTable").innerHTML=tableHTML("Grupo único · Los 4 mejores avanzan",stats(WOMEN,ms.filter(m=>m.gender==="F")))}
async function renderMatches(){let ms=await getMatches();let days={};ms.forEach(m=>(days[m.day]??=[]).push(m));document.getElementById("matches").innerHTML=Object.entries(days).map(([d,a])=>`<div class="matchday"><h3>Día ${d}</h3>${a.map(m=>`<div class="match"><span>${m.gender==="M"?"Hombres":"Mujeres"}</span><strong>${m.home_team} vs ${m.away_team}</strong><span class="score">${m.home_score==null?"—":m.home_score+" - "+m.away_score}</span>${session?`<button class="outline edit" onclick="editMatch('${m.id}','${m.home_team}','${m.away_team}',${m.home_score??"null"},${m.away_score??"null"})">Editar</button>`:""}</div>`).join("")}</div>`).join("")||'<div class="empty">No hay partidos cargados.</div>'}
async function renderNext(){let ms=await getMatches();let n=ms.find(m=>m.home_score==null||m.away_score==null);document.getElementById("nextMatch").innerHTML=n?`<small>PRÓXIMO PARTIDO · DÍA ${n.day}</small><h2>${n.home_team} vs ${n.away_team}</h2><p>${n.gender==="M"?"Hombres":"Mujeres"}</p>`:"<h2>Todos los partidos tienen resultado.</h2>"}
function editMatch(id,h,a,hs,as){document.getElementById("editTitle").textContent=`${h} vs ${a}`;document.getElementById("editBody").innerHTML=`<input id="hs" type="number" min="0" value="${hs===null?"":hs}" placeholder="Goles ${h}"><input id="as" type="number" min="0" value="${as===null?"":as}" placeholder="Goles ${a}"><button class="primary" onclick="saveMatch('${id}')">Guardar resultado</button>`;document.getElementById("editModal").classList.remove("hidden")}
async function saveMatch(id){let hs=document.getElementById("hs").value,as=document.getElementById("as").value;if(hs===""||as==="")return;let {error}=await db.from("matches").update({home_score:+hs,away_score:+as}).eq("id",id);if(error)alert(error.message);else{closeEdit();refresh()}}
async function renderSanctions(){if(!db){document.getElementById("sanctions").innerHTML='<div class="empty">Conecta Supabase para activar sanciones.</div>';return}let {data,error}=await db.from("sanctions").select("*").order("created_at",{ascending:false});if(error){document.getElementById("sanctions").innerHTML='<div class="empty">Configura la base de datos para ver sanciones.</div>';return}document.getElementById("sanctions").innerHTML=data.length?data.map(s=>`<div class="sanction"><strong>${s.team}</strong><span>${s.player||"—"}</span><span>${s.type}</span><span>${s.description||""}</span>${session?`<button class="danger" onclick="deleteSanction('${s.id}')">Eliminar</button>`:""}</div>`).join(""):'<div class="empty">No hay sanciones registradas.</div>'}
function openSanctionForm(){document.getElementById("editTitle").textContent="Agregar sanción";document.getElementById("editBody").innerHTML=`<input id="st" placeholder="Equipo"><input id="sp" placeholder="Jugador (opcional)"><select id="sy"><option>Tarjeta amarilla</option><option>Tarjeta roja</option><option>Suspensión</option><option>Otra</option></select><textarea id="sd" placeholder="Descripción"></textarea><button class="primary" onclick="saveSanction()">Guardar sanción</button>`;document.getElementById("editModal").classList.remove("hidden")}
async function saveSanction(){let payload={team:st.value,player:sp.value,type:sy.value,description:sd.value};let {error}=await db.from("sanctions").insert(payload);if(error)alert(error.message);else{closeEdit();renderSanctions()}}
async function deleteSanction(id){if(confirm("¿Eliminar esta sanción?")){await db.from("sanctions").delete().eq("id",id);renderSanctions()}}
function renderDemo(){document.getElementById("menTables").innerHTML=tableHTML("Grupo A",stats(MEN_A,[{home_team:"Fortnite",away_team:"Chifladitos",home_score:1,away_score:0}]));document.getElementById("menTables").innerHTML+=tableHTML("Grupo B",stats(MEN_B,[{home_team:"Sin Esquinas",away_team:"Motoneta",home_score:2,away_score:1}]));document.getElementById("womenTable").innerHTML=tableHTML("Grupo único · Los 4 mejores avanzan",stats(WOMEN,[]));document.getElementById("matches").innerHTML='<div class="empty">Modo demo. Configura Supabase para edición compartida.</div>';document.getElementById("sanctions").innerHTML='<div class="empty">Las sanciones aparecerán aquí al conectar Supabase.</div>';document.getElementById("nextMatch").innerHTML="<small>DEMO</small><h2>Configura la base de datos para activar el calendario.</h2>"}
